export const ADMIN_GET_ALL_USERS_REQUEST = 'ADMIN_GET_ALL_USERS_REQUEST'
export const ADMIN_GET_ALL_USERS_SUCCESS = 'ADMIN_GET_ALL_USERS_SUCCESS'
export const ADMIN_GET_ALL_USERS_FAIL = 'ADMIN_GET_ALL_USERS_FAIL'

export const ADMIN_UPDATE_USER_REQUEST = 'ADMIN_UPDATE_USER_REQUEST'
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS'
export const ADMIN_UPDATE_USER_FAIL = 'ADMIN_UPDATE_USER_FAIL'

export const ADMIN_DELETE_USER_REQUEST = 'ADMIN_DELETE_USER_REQUEST'
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS'
export const ADMIN_DELETE_USER_FAIL = 'ADMIN_DELETE_USER_FAIL'

export const ADMIN_GET_ALL_QUESTIONS_REQUEST = 'ADMIN_GET_ALL_QUESTIONS_REQUEST'
export const ADMIN_GET_ALL_QUESTIONS_SUCCESS = 'ADMIN_GET_ALL_QUESTIONS_SUCCESS'
export const ADMIN_GET_ALL_QUESTIONS_FAIL = 'ADMIN_GET_ALL_QUESTIONS_FAIL'

export const ADMIN_UPDATE_QUESTION_REQUEST = 'ADMIN_UPDATE_QUESTION_REQUEST'
export const ADMIN_UPDATE_QUESTION_SUCCESS = 'ADMIN_UPDATE_QUESTION_SUCCESS'
export const ADMIN_UPDATE_QUESTION_FAIL = 'ADMIN_UPDATE_QUESTION_FAIL'

export const ADMIN_CREATE_QUESTION_REQUEST = 'ADMIN_CREATE_QUESTION_REQUEST'
export const ADMIN_CREATE_QUESTION_SUCCESS = 'ADMIN_CREATE_QUESTION_SUCCESS'
export const ADMIN_CREATE_QUESTION_FAIL = 'ADMIN_CREATE_QUESTION_FAIL'

export const ADMIN_DELETE_QUESTION_REQUEST = 'ADMIN_DELETE_QUESTION_REQUEST'
export const ADMIN_DELETE_QUESTION_SUCCESS = 'ADMIN_DELETE_QUESTION_SUCCESS'
export const ADMIN_DELETE_QUESTION_FAIL = 'ADMIN_DELETE_QUESTION_FAIL'
