export const CHART_GET_ALL_OWNER_REQUEST = ' CHART_GET_ALL_OWNER_REQUEST'
export const CHART_GET_ALL_OWNER_SUCCESS = ' CHART_GET_ALL_OWNER_SUCCESS'
export const CHART_GET_ALL_OWNER_FAIL = ' CHART_GET_ALL_OWNER_FAIL'

export const CHART_GET_ONE_REQUEST = ' CHART_GET_ONE_REQUEST'
export const CHART_GET_ONE_SUCCESS = ' CHART_GET_ONE_SUCCESS'
export const CHART_GET_ONE_FAIL = ' CHART_GET_ONE_FAIL'

export const CHART_CREATE_REQUEST = ' CHART_CREATE_REQUEST'
export const CHART_CREATE_SUCCESS = ' CHART_CREATE_SUCCESS'
export const CHART_CREATE_FAIL = ' CHART_CREATE_FAIL'

export const CHART_UPDATE_REQUEST = ' CHART_UPDATE_REQUEST'
export const CHART_UPDATE_SUCCESS = ' CHART_UPDATE_SUCCESS'
export const CHART_UPDATE_FAIL = ' CHART_UPDATE_FAIL'
