export const INVITATION_CREATE_REQUEST = 'INVITATION_CREATE_REQUEST'
export const INVITATION_CREATE_SUCCESS = 'INVITATION_CREATE_SUCCESS'
export const INVITATION_CREATE_FAIL = 'INVITATION_CREATE_FAIL'

export const INVITATION_DELETE_REQUEST = 'INVITATION_DELETE_REQUEST'
export const INVITATION_DELETE_SUCCESS = 'INVITATION_DELETE_SUCCESS'
export const INVITATION_DELETE_FAIL = 'INVITATION_DELETE_FAIL'
