export const TEAM_CREATE_REQUEST = 'TEAM_CREATE_REQUEST'
export const TEAM_CREATE_SUCCESS = 'TEAM_CREATE_SUCCESS'
export const TEAM_CREATE_FAIL = 'TEAM_CREATE_FAIL'

export const TEAM_GET_ALL_REQUEST = 'TEAM_GET_ALL_REQUEST'
export const TEAM_GET_ALL_SUCCESS = 'TEAM_GET_ALL_SUCCESS'
export const TEAM_GET_ALL_FAIL = 'TEAM_GET_ALL_FAIL'

export const TEAM_GET_ONE_REQUEST = 'TEAM_GET_ONE_REQUEST'
export const TEAM_GET_ONE_SUCCESS = 'TEAM_GET_ONE_SUCCESS'
export const TEAM_GET_ONE_FAIL = 'TEAM_GET_ONE_FAIL'

export const TEAM_UPDATE_REQUEST = 'TEAM_UPDATE_REQUEST'
export const TEAM_UPDATE_SUCCESS = 'TEAM_UPDATE_SUCCESS'
export const TEAM_UPDATE_FAIL = 'TEAM_UPDATE_FAIL'

export const TEAM_DELETE_REQUEST = 'TEAM_DELETE_REQUEST'
export const TEAM_DELETE_SUCCESS = 'TEAM_DELETE_SUCCESS'
export const TEAM_DELETE_FAIL = 'TEAM_DELETE_FAIL'

export const TEAM_JOIN_REQUEST = 'TEAM_JOIN_REQUEST'
export const TEAM_JOIN_SUCCESS = 'TEAM_JOIN_SUCCESS'
export const TEAM_JOIN_FAIL = 'TEAM_JOIN_FAIL'
