export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_GET_ALL_REQUEST = 'USER_GET_ALL_REQUEST'
export const USER_GET_ALL_SUCCESS = 'USER_GET_ALL_SUCCESS'
export const USER_GET_ALL_FAIL = 'USER_GET_ALL_FAIL'

export const USER_GET_ONE_REQUEST = 'USER_GET_ONE_REQUEST'
export const USER_GET_ONE_SUCCESS = 'USER_GET_ONE_SUCCESS'
export const USER_GET_ONE_FAIL = 'USER_GET_ONE_FAIL'

export const USER_UPDATE_ONE_REQUEST = 'USER_UPDATE_ONE_REQUEST'
export const USER_UPDATE_ONE_SUCCESS = 'USER_UPDATE_ONE_SUCCESS'
export const USER_UPDATE_ONE_FAIL = 'USER_UPDATE_ONE_FAIL'

export const UPDATE_ME_REQUEST = 'UPDATE_ME_REQUEST'
export const UPDATE_ME_SUCCESS = 'UPDATE_ME_SUCCESS'
export const UPDATE_ME_FAIL = 'UPDATE_ME_FAIL'
